local credits = {}

table.insert(credits, 	{"Darren Cook" , "Ken DeLozier"}	)
table.insert(credits, 	{"Claire Cook" , "Tara Ochs"}	)
table.insert(credits, 	{"Chloe Cook" , "Katelyn Nacon"}	)
table.insert(credits, 	{"Harry Cook" , "Justin Scott"}	)
table.insert(credits, 	{"Savannah Cook" , "Morgan Burch"}	)
table.insert(credits, 	{"Veronica Van Cook" , "Linda Miller"}	)
table.insert(credits, 	{"Jenny Cook" , "Layla Neal"}	)
table.insert(credits, 	{"Melinda Cook" , "Kayte Giralt"}	)
table.insert(credits, 	{"Taylor Cook" , "Truman Orr"}	)
table.insert(credits, 	{"Olivia Cook" , "Jayla James"}	)
table.insert(credits, 	{"Warren O'Cook" , "Cameron Markeles"}	)
table.insert(credits, 	{"Jim Cook" , "Zack Shires"}	)
table.insert(credits, 	{"Armondo Del Cook" , "Gwydion Lashlee-Walton"}	)
table.insert(credits, 	{"Zoe Cook" , "Ginny Gibbons"}	)
table.insert(credits, 	{"Dave Cook" , "Dylan Schoenthal"}	)
table.insert(credits, 	{"Thomas Van Cook IV" , "Logan Schoenthal"}	)
table.insert(credits, 	{"Grammy Cook" , "Barbara Bruce"}	)
table.insert(credits, 	{"Sasha Cook" , "Mary McGahren"}	)
table.insert(credits, 	{"Cody Cook" , "Ricky Boynton"}	)
table.insert(credits, 	{"Logan O'Cook" , "V.C. Fuqua"}	)
table.insert(credits, 	{"Melissa Cook" , "Nilsa Castro"}	)
table.insert(credits, 	{"Caleb Cook" , "Gregory Rose"}	)
table.insert(credits, 	{"Chris Cook" , "Will Dove"}	)
table.insert(credits, 	{"Marilyn McCook" , "Victoria Sun"}	)
table.insert(credits, 	{"T.L. Cook" , "Marc Farley"}	)
table.insert(credits, 	{"Archer Cook" , "Charles Pittard"}	)
table.insert(credits, 	{"Aimee Cook" , "Karen Cassady"}	)
table.insert(credits, 	{"Alex Cook" , "Michael Jenkins"}	)
table.insert(credits, 	{"Stanislav Cook" , "Chris Riley"}	)
table.insert(credits, 	{"Ashley Cook" , "Tina Bandoo"}	)
table.insert(credits, 	{"Linda Cook" , "Cynthia Jenkins"}	)
table.insert(credits, 	{"Louise Cook" , "Sheila Agnew McCoy"}	)
table.insert(credits, 	{"Jebediah Cook" , "Clayton Russell"}	)
table.insert(credits, 	{"Laura Cook" , "Ali Froid"}	)
table.insert(credits, 	{"Ralph Cook" , "Edward Kercado"}	)
table.insert(credits, 	{"D.C. 'Fingers' Cook" , "Josh Lowder"}	)
table.insert(credits, 	{"Sgt. Cook" , "James White"}	)
table.insert(credits, 	{"Det. Derrick Cook" , "Eugene Jackson"}	)
table.insert(credits, 	{"Captain James Cook" , "Nick Gibbons"}	)
table.insert(credits, 	{"Coat" , "Matt Foster"}	)
table.insert(credits, 	{"Athena Cook" , "Candace Mabry"}	)
table.insert(credits, 	{"Tecumseh Cook" , "Ben Peck"}	)
table.insert(credits, 	{"Chad Cook" , "Dan Triandiflou"}	)
table.insert(credits, 	{"Pam Cook" , "Elena Nordé"}	)
table.insert(credits, 	{"Lori Cook" , "Amy Rollins"}	)
table.insert(credits, 	{"Samantha Cook" , "Katie Adkins"}	)
table.insert(credits, 	{"B6-12" , "John Skowronski"}	)
table.insert(credits, 	{"Sebastian Cook" , "Tony Holley"}	)
table.insert(credits, 	{"Det. W. J. Cookowski" , "Derick Huffmaster"}	)
table.insert(credits, 	{"V.O. Cook" , "John Garry"}	)
table.insert(credits, 	{"Commodore Montgomery Cook" , "Steve Bowlin"}	)
table.insert(credits, 	{"Lance Starcook" , "John Crow"}	)
table.insert(credits, 	{"Flizzrton'dk C.O.O.K." , "Matthew Sparks"}	)
table.insert(credits, 	{"Capt. Jen Simmer" , "Jennifer Giles"}	)
table.insert(credits, 	{"Doctor Shazznarlk" , "Matt Burke"}	)
table.insert(credits, 	{"Ben Bake" , "Jeffrey Kim"}	)
table.insert(credits, 	{"Dr. Bennett Hamilton Cooke" , "John Curran"}	)
table.insert(credits, 	{"Dr. Alexis Wentworth Cooke" , "Mary Kraft"}	)
table.insert(credits, 	{"Roy Broil" , "Aurangzeb Haq"}	)
table.insert(credits, 	{"Juggler Cook" , "Jonathan Jackson"}	)
table.insert(credits, 	{"Benji Cooke" , "Cameron Boling"}	)
table.insert(credits, 	{"Travis Cook" , "Oz Shaw"}	)
table.insert(credits, 	{"Fifi Cook" , "Heather Kelly"}	)
table.insert(credits, 	{"McGillicutty Cook" , "Ava Kelly"}	)
table.insert(credits, 	{"Poppy Cook" , "Maggie Kelly"}	)
table.insert(credits, 	{"Chloe Bush" , "Rachel DeJulio"}	)
table.insert(credits, 	{"Also Featuring" , "William Tokarsky"}	)
return credits
