
local wallTypes = {
	outCorner_NW = {index = 1, rotation = 0},
	outCorner_SW = {index = 1, rotation = 3},
	outCorner_SE = {index = 1, rotation = 2},
	outCorner_NE = {index = 1, rotation = 1},

	inCorner_SE = {index = 2, rotation = 0},
	inCorner_NE = {index = 2, rotation = 3},
	inCorner_NW = {index = 2, rotation = 2},
	inCorner_SW = {index = 2, rotation = 1},

	single_W = {index = 3, rotation = 0},
	single_S = {index = 3, rotation = 3},
	single_E = {index = 3, rotation = 2},
	single_N = {index = 3, rotation = 1},

	filler = {index = 4, rotation = 0},

	outBend_NW = {index = 5, rotation = 0},
	outBend_SW = {index = 5, rotation = 3},
	outBend_SE = {index = 5, rotation = 2},
	outBend_NE = {index = 5, rotation = 1},

	half_T1_SE = {index = 6, rotation = 0},
	half_T1_NE = {index = 6, rotation = 3},
	half_T1_SW = {index = 6, rotation = 1},
	half_T1_NW = {index = 6, rotation = 2},

 	T_N= {index = 7, rotation = 0},
 	T_W= {index = 7, rotation = 3},
 	T_S= {index = 7, rotation = 2},
 	T_E= {index = 7, rotation = 1},

	half_T2_NE = {index = 8, rotation = 0},
	half_T2_NW = {index = 8, rotation = 3},
	half_T2_SW = {index = 8, rotation = 2},
	half_T2_SE = {index = 8, rotation = 1},

	doubleCorner_LR_A = {index = 9, rotation = 0},
	doubleCorner_LR_D = {index = 9, rotation = 1},

	tripleCorner_SE = {index = 10, rotation = 0},
	tripleCorner_NE = {index = 10, rotation = 3},
	tripleCorner_NW = {index = 10, rotation = 2},
	tripleCorner_SW = {index = 10, rotation = 1},

	cross = {index = 11, rotation = 0},

	doubleSided_V = {index = 12, rotation = 0},
	doubleSided_H = {index = 12, rotation = 1},

	doubleCorner_N = {index = 13, rotation = 0},
	doubleCorner_W = {index = 13, rotation = 3},
	doubleCorner_S = {index = 13, rotation = 2},
	doubleCorner_E = {index = 13, rotation = 1},

	outset_S = {index = 14, rotation = 0},
	outset_E = {index = 14, rotation = 3},
	outset_N = {index = 14, rotation = 2},
	outset_W = {index = 14, rotation = 1},

	island = {index = 15, rotation = 0},
}

for _, wallData in pairs(wallTypes) do
	wallData.rotation = (wallData.rotation*-1)/4
end

return {
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.outset_W,
	wallTypes.outBend_SW,
	wallTypes.outset_W,
	wallTypes.outCorner_SW,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.outset_W,
	wallTypes.outBend_SW,
	wallTypes.outset_W,
	wallTypes.outCorner_SW,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outBend_NW,
	wallTypes.T_W,
	wallTypes.outBend_NW,
	wallTypes.half_T2_SE,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outCorner_NW,
	wallTypes.half_T1_NE,
	wallTypes.outCorner_NW,
	wallTypes.single_W,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.outset_W,
	wallTypes.outBend_SW,
	wallTypes.outset_W,
	wallTypes.outCorner_SW,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.outset_W,
	wallTypes.outBend_SW,
	wallTypes.outset_W,
	wallTypes.outCorner_SW,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outBend_NW,
	wallTypes.T_W,
	wallTypes.outBend_NW,
	wallTypes.half_T2_SE,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outCorner_NW,
	wallTypes.half_T1_NE,
	wallTypes.outCorner_NW,
	wallTypes.single_W,
	wallTypes.outset_E,
	wallTypes.outBend_SE,
	wallTypes.outset_E,
	wallTypes.outBend_SE,
	wallTypes.doubleSided_H,
	wallTypes.T_S,
	wallTypes.doubleSided_H,
	wallTypes.half_T1_NW,
	wallTypes.outset_E,
	wallTypes.outBend_SE,
	wallTypes.outset_E,
	wallTypes.outBend_SE,
	wallTypes.doubleSided_H,
	wallTypes.T_S,
	wallTypes.doubleSided_H,
	wallTypes.half_T1_NW,
	wallTypes.outBend_NE,
	wallTypes.T_E,
	wallTypes.outBend_NE,
	wallTypes.T_E,
	wallTypes.T_N,
	wallTypes.cross,
	wallTypes.T_N,
	wallTypes.tripleCorner_NE,
	wallTypes.outBend_NE,
	wallTypes.T_E,
	wallTypes.outBend_NE,
	wallTypes.T_E,
	wallTypes.half_T2_SW,
	wallTypes.tripleCorner_SE,
	wallTypes.half_T2_SW,
	wallTypes.doubleCorner_E,
	wallTypes.outset_E,
	wallTypes.outBend_SE,
	wallTypes.outset_E,
	wallTypes.outBend_SE,
	wallTypes.doubleSided_H,
	wallTypes.T_S,
	wallTypes.doubleSided_H,
	wallTypes.half_T1_NW,
	wallTypes.outset_E,
	wallTypes.outBend_SE,
	wallTypes.outset_E,
	wallTypes.outBend_SE,
	wallTypes.doubleSided_H,
	wallTypes.T_S,
	wallTypes.doubleSided_H,
	wallTypes.half_T1_NW,
	wallTypes.outCorner_NE,
	wallTypes.half_T2_NW,
	wallTypes.outCorner_NE,
	wallTypes.half_T2_NW,
	wallTypes.half_T1_SE,
	wallTypes.tripleCorner_SW,
	wallTypes.half_T1_SE,
	wallTypes.doubleCorner_LR_D,
	wallTypes.outCorner_NE,
	wallTypes.half_T2_NW,
	wallTypes.outCorner_NE,
	wallTypes.half_T2_NW,
	wallTypes.single_N,
	wallTypes.doubleCorner_S,
	wallTypes.single_N,
	wallTypes.inCorner_NW,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.outset_W,
	wallTypes.outBend_SW,
	wallTypes.outset_W,
	wallTypes.outCorner_SW,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.outset_W,
	wallTypes.outBend_SW,
	wallTypes.outset_W,
	wallTypes.outCorner_SW,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outBend_NW,
	wallTypes.T_W,
	wallTypes.outBend_NW,
	wallTypes.half_T2_SE,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outCorner_NW,
	wallTypes.half_T1_NE,
	wallTypes.outCorner_NW,
	wallTypes.single_W,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.outset_W,
	wallTypes.outBend_SW,
	wallTypes.outset_W,
	wallTypes.outCorner_SW,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.island,
	wallTypes.outset_S,
	wallTypes.outset_W,
	wallTypes.outBend_SW,
	wallTypes.outset_W,
	wallTypes.outCorner_SW,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outBend_NW,
	wallTypes.T_W,
	wallTypes.outBend_NW,
	wallTypes.half_T2_SE,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outset_N,
	wallTypes.doubleSided_V,
	wallTypes.outCorner_NW,
	wallTypes.half_T1_NE,
	wallTypes.outCorner_NW,
	wallTypes.single_W,
	wallTypes.outset_E,
	wallTypes.outCorner_SE,
	wallTypes.outset_E,
	wallTypes.outCorner_SE,
	wallTypes.doubleSided_H,
	wallTypes.half_T2_NE,
	wallTypes.doubleSided_H,
	wallTypes.single_S,
	wallTypes.outset_E,
	wallTypes.outCorner_SE,
	wallTypes.outset_E,
	wallTypes.outCorner_SE,
	wallTypes.doubleSided_H,
	wallTypes.half_T2_NE,
	wallTypes.doubleSided_H,
	wallTypes.single_S,
	wallTypes.outBend_NE,
	wallTypes.half_T1_SW,
	wallTypes.outBend_NE,
	wallTypes.half_T1_SW,
	wallTypes.T_N,
	wallTypes.tripleCorner_NW,
	wallTypes.T_N,
	wallTypes.doubleCorner_N,
	wallTypes.outBend_NE,
	wallTypes.half_T1_SW,
	wallTypes.outBend_NE,
	wallTypes.half_T1_SW,
	wallTypes.half_T2_SW,
	wallTypes.doubleCorner_LR_A,
	wallTypes.half_T2_SW,
	wallTypes.inCorner_SW,
	wallTypes.outset_E,
	wallTypes.outCorner_SE,
	wallTypes.outset_E,
	wallTypes.outCorner_SE,
	wallTypes.doubleSided_H,
	wallTypes.half_T2_NE,
	wallTypes.doubleSided_H,
	wallTypes.single_S,
	wallTypes.outset_E,
	wallTypes.outCorner_SE,
	wallTypes.outset_E,
	wallTypes.outCorner_SE,
	wallTypes.doubleSided_H,
	wallTypes.half_T2_NE,
	wallTypes.doubleSided_H,
	wallTypes.single_S,
	wallTypes.outCorner_NE,
	wallTypes.single_E,
	wallTypes.outCorner_NE,
	wallTypes.single_E,
	wallTypes.half_T1_SE,
	wallTypes.doubleCorner_W,
	wallTypes.half_T1_SE,
	wallTypes.inCorner_SE,
	wallTypes.outCorner_NE,
	wallTypes.single_E,
	wallTypes.outCorner_NE,
	wallTypes.single_E,
	wallTypes.single_N,
	wallTypes.inCorner_NE,
	wallTypes.single_N,
	wallTypes.filler
}
